server:
  port: 8761

security:
  basic:
    enabled: true
  user:
    name: mogu
    password: mogu

spring:
  jmx:
    default-domain: mogu_eureka  

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://mogu:mogu@localhost:8761/eureka