server:
  port: 9527
  servlet:
    context-path: /

spring:
  jmx:
    default-domain: cutter_point_zuul
  application:
    name: cutter-point-zuul
    # DATABASE CONFIG
  datasource:
    username: cutter_point
    password: cutter_point
    url: jdbc:mysql://192.168.0.104:3306/cutter_point?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 50
    #连接等待超时时间
    maxWait: 60000
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    timeBetweenEvictionRunsMillis: 60000
    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    dbcp:
      remove-abandoned: true
      #泄露的连接可以被删除的超时时间（秒），该值应设置为应用程序查询可能执行的最长时间
      remove-abandoned-timeout: 180
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #从Eureka Server获取注册信息
    service-url:
      defaultZone: http://192.168.0.104:8761/cutter-point-eureka/eureka/
  instance:
    appname: cutter-point-zuul

#设置zuul请求路由，所有service1的请求进入cutter-point-service1，2的进入cutter-point-http
zuul:
  routes:
    cutter-point-monitor:
      stripPrefix: false
      path: /cutter-point-monitor/**
      serviceId: cutter-point-monitor
    cutter-point-blog-web:
      stripPrefix: false
      path: /cutter-point-blog-web/**
      serviceId: cutter-point-blog-web
    cutter-point-picture:
      stripPrefix: false
      path: /cutter-point-blog-picture/**
      serviceId: cutter-point-blog-picture
    cutter-point-blog-admin:
      stripPrefix: false
      path: /cutter-point-blog-admin/**
      serviceId: cutter-point-blog-admin
    #直接转发ip请求
    users:
      path: /admin/**
      url: http://127.0.0.1:9528/admin
  #  zuul默认对转发的request，会把header清空，为了传递原始的header信息到最终的微服务，在配置加上：(对，你没看错，就是为空，yml格式也是）
  # 这里是配置过滤的规则，也就是配什么，就拦截什么
  #  zuul.sensitive-headers=
  #
  #  上面是全局的，也可定义局部了，会覆盖全局的设置：
  #  zuul.routes.xxxapi-xxx.sensitive-headers=
  #  或者个性化：
  #  zuul.routes.<xxxapi-xxx>.custom-sensitive-headers=true
  #  zuul.routes.<xxxapi-xxx>.sensitive-headers=Cookie,Set-Cookie,Authorization
  sensitive-headers:


ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
